server:
  port: 9002
  address: 10.194.186.230
spring:
  application:
    name: cloud-publicservice


eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:bmsoft@10.194.186.228:4000/eureka
  instance:
    metadata-map:
      test: wedatasphere

management:
  endpoints:
    web:
      exposure:
        include: refresh,info
logging:
  config: classpath:log4j2.xml

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql
