server:
  port: 9821
spring:
  application:
    name: dependency


eureka:
  client:
    serviceUrl:
      defaultZone: http://10.194.186.230:20303/eureka/
  instance:
    metadata-map:
      test: wedatasphere

management:
  endpoints:
    web:
      exposure:
        include: refresh,info
