server:
  port: 9003
spring:
  application:
    name: ResourceManager


eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:bmsoft@10.194.186.228:4000/eureka
  instance:
    metadata-map:
      test: wedatasphere

management:
  endpoints:
    web:
      exposure:
        include: refresh,info
