server:
  port: 9001
spring:
  application:
    name: DataWorkCloud-Gateway
  cloud:
    gateway:
      routes:
        - id: dws
          uri: http://localhost:port/
          predicates:
          - Path=/dws/
        - id: dws/vg
          uri: http://localhost:port/
          predicates:
          - Path=/dws/vg/
        - id: dws/easyide
          uri: http://localhost:port/
          predicates:
          - Path=/dws/easyide/

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:bmsoft@10.194.186.228:4000/eureka
    registry-fetch-interval-seconds: 5
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    prefer-ip-address: true


management:
  endpoints:
    web:
      exposure:
        include: refresh,info
