server:
  port: 7863
spring:
  application:
    name: cloud-areyouok


eureka:
  client:
    serviceUrl:
      defaultZone: locahost
  instance:
    metadata-map:
      test: wedatasphere

management:
  endpoints:
    web:
      exposure:
        include: refresh,info
logging:
  config: classpath:log4j2.xml